// flow-typed signature: 707dc8ad343bbbc20eb3bda63ab382df
// flow-typed version: <<STUB>>/asap_v2.0.5/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'asap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'asap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'asap/asap' {
  declare module.exports: any;
}

declare module 'asap/browser-asap' {
  declare module.exports: any;
}

declare module 'asap/browser-raw' {
  declare module.exports: any;
}

declare module 'asap/raw' {
  declare module.exports: any;
}

// Filename aliases
declare module 'asap/asap.js' {
  declare module.exports: $Exports<'asap/asap'>;
}
declare module 'asap/browser-asap.js' {
  declare module.exports: $Exports<'asap/browser-asap'>;
}
declare module 'asap/browser-raw.js' {
  declare module.exports: $Exports<'asap/browser-raw'>;
}
declare module 'asap/raw.js' {
  declare module.exports: $Exports<'asap/raw'>;
}
