// flow-typed signature: 73f80e6959ae24525007e9f8829f4f9d
// flow-typed version: <<STUB>>/enzyme_v2.8.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enzyme/build/ComplexSelector' {
  declare module.exports: any;
}

declare module 'enzyme/build/Debug' {
  declare module.exports: any;
}

declare module 'enzyme/build/index' {
  declare module.exports: any;
}

declare module 'enzyme/build/mount' {
  declare module.exports: any;
}

declare module 'enzyme/build/MountedTraversal' {
  declare module.exports: any;
}

declare module 'enzyme/build/react-compat' {
  declare module.exports: any;
}

declare module 'enzyme/build/ReactWrapper' {
  declare module.exports: any;
}

declare module 'enzyme/build/ReactWrapperComponent' {
  declare module.exports: any;
}

declare module 'enzyme/build/render' {
  declare module.exports: any;
}

declare module 'enzyme/build/shallow' {
  declare module.exports: any;
}

declare module 'enzyme/build/ShallowTraversal' {
  declare module.exports: any;
}

declare module 'enzyme/build/ShallowWrapper' {
  declare module.exports: any;
}

declare module 'enzyme/build/Utils' {
  declare module.exports: any;
}

declare module 'enzyme/build/version' {
  declare module.exports: any;
}

declare module 'enzyme/karma.conf' {
  declare module.exports: any;
}

declare module 'enzyme/mount' {
  declare module.exports: any;
}

declare module 'enzyme/ReactWrapper' {
  declare module.exports: any;
}

declare module 'enzyme/render' {
  declare module.exports: any;
}

declare module 'enzyme/shallow' {
  declare module.exports: any;
}

declare module 'enzyme/ShallowWrapper' {
  declare module.exports: any;
}

declare module 'enzyme/src/ComplexSelector' {
  declare module.exports: any;
}

declare module 'enzyme/src/Debug' {
  declare module.exports: any;
}

declare module 'enzyme/src/index' {
  declare module.exports: any;
}

declare module 'enzyme/src/mount' {
  declare module.exports: any;
}

declare module 'enzyme/src/MountedTraversal' {
  declare module.exports: any;
}

declare module 'enzyme/src/react-compat' {
  declare module.exports: any;
}

declare module 'enzyme/src/ReactWrapper' {
  declare module.exports: any;
}

declare module 'enzyme/src/ReactWrapperComponent' {
  declare module.exports: any;
}

declare module 'enzyme/src/render' {
  declare module.exports: any;
}

declare module 'enzyme/src/shallow' {
  declare module.exports: any;
}

declare module 'enzyme/src/ShallowTraversal' {
  declare module.exports: any;
}

declare module 'enzyme/src/ShallowWrapper' {
  declare module.exports: any;
}

declare module 'enzyme/src/Utils' {
  declare module.exports: any;
}

declare module 'enzyme/src/version' {
  declare module.exports: any;
}

declare module 'enzyme/test/_helpers/index' {
  declare module.exports: any;
}

declare module 'enzyme/test/_helpers/react-compat' {
  declare module.exports: any;
}

declare module 'enzyme/test/ComplexSelector-spec' {
  declare module.exports: any;
}

declare module 'enzyme/test/Debug-spec' {
  declare module.exports: any;
}

declare module 'enzyme/test/ReactWrapper-spec' {
  declare module.exports: any;
}

declare module 'enzyme/test/ShallowTraversal-spec' {
  declare module.exports: any;
}

declare module 'enzyme/test/ShallowWrapper-spec' {
  declare module.exports: any;
}

declare module 'enzyme/test/staticRender-spec' {
  declare module.exports: any;
}

declare module 'enzyme/test/Utils-spec' {
  declare module.exports: any;
}

declare module 'enzyme/withDom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enzyme/build/ComplexSelector.js' {
  declare module.exports: $Exports<'enzyme/build/ComplexSelector'>;
}
declare module 'enzyme/build/Debug.js' {
  declare module.exports: $Exports<'enzyme/build/Debug'>;
}
declare module 'enzyme/build/index.js' {
  declare module.exports: $Exports<'enzyme/build/index'>;
}
declare module 'enzyme/build/mount.js' {
  declare module.exports: $Exports<'enzyme/build/mount'>;
}
declare module 'enzyme/build/MountedTraversal.js' {
  declare module.exports: $Exports<'enzyme/build/MountedTraversal'>;
}
declare module 'enzyme/build/react-compat.js' {
  declare module.exports: $Exports<'enzyme/build/react-compat'>;
}
declare module 'enzyme/build/ReactWrapper.js' {
  declare module.exports: $Exports<'enzyme/build/ReactWrapper'>;
}
declare module 'enzyme/build/ReactWrapperComponent.js' {
  declare module.exports: $Exports<'enzyme/build/ReactWrapperComponent'>;
}
declare module 'enzyme/build/render.js' {
  declare module.exports: $Exports<'enzyme/build/render'>;
}
declare module 'enzyme/build/shallow.js' {
  declare module.exports: $Exports<'enzyme/build/shallow'>;
}
declare module 'enzyme/build/ShallowTraversal.js' {
  declare module.exports: $Exports<'enzyme/build/ShallowTraversal'>;
}
declare module 'enzyme/build/ShallowWrapper.js' {
  declare module.exports: $Exports<'enzyme/build/ShallowWrapper'>;
}
declare module 'enzyme/build/Utils.js' {
  declare module.exports: $Exports<'enzyme/build/Utils'>;
}
declare module 'enzyme/build/version.js' {
  declare module.exports: $Exports<'enzyme/build/version'>;
}
declare module 'enzyme/karma.conf.js' {
  declare module.exports: $Exports<'enzyme/karma.conf'>;
}
declare module 'enzyme/mount.js' {
  declare module.exports: $Exports<'enzyme/mount'>;
}
declare module 'enzyme/ReactWrapper.js' {
  declare module.exports: $Exports<'enzyme/ReactWrapper'>;
}
declare module 'enzyme/render.js' {
  declare module.exports: $Exports<'enzyme/render'>;
}
declare module 'enzyme/shallow.js' {
  declare module.exports: $Exports<'enzyme/shallow'>;
}
declare module 'enzyme/ShallowWrapper.js' {
  declare module.exports: $Exports<'enzyme/ShallowWrapper'>;
}
declare module 'enzyme/src/ComplexSelector.js' {
  declare module.exports: $Exports<'enzyme/src/ComplexSelector'>;
}
declare module 'enzyme/src/Debug.js' {
  declare module.exports: $Exports<'enzyme/src/Debug'>;
}
declare module 'enzyme/src/index.js' {
  declare module.exports: $Exports<'enzyme/src/index'>;
}
declare module 'enzyme/src/mount.js' {
  declare module.exports: $Exports<'enzyme/src/mount'>;
}
declare module 'enzyme/src/MountedTraversal.js' {
  declare module.exports: $Exports<'enzyme/src/MountedTraversal'>;
}
declare module 'enzyme/src/react-compat.js' {
  declare module.exports: $Exports<'enzyme/src/react-compat'>;
}
declare module 'enzyme/src/ReactWrapper.jsx' {
  declare module.exports: $Exports<'enzyme/src/ReactWrapper'>;
}
declare module 'enzyme/src/ReactWrapperComponent.jsx' {
  declare module.exports: $Exports<'enzyme/src/ReactWrapperComponent'>;
}
declare module 'enzyme/src/render.jsx' {
  declare module.exports: $Exports<'enzyme/src/render'>;
}
declare module 'enzyme/src/shallow.js' {
  declare module.exports: $Exports<'enzyme/src/shallow'>;
}
declare module 'enzyme/src/ShallowTraversal.js' {
  declare module.exports: $Exports<'enzyme/src/ShallowTraversal'>;
}
declare module 'enzyme/src/ShallowWrapper.js' {
  declare module.exports: $Exports<'enzyme/src/ShallowWrapper'>;
}
declare module 'enzyme/src/Utils.js' {
  declare module.exports: $Exports<'enzyme/src/Utils'>;
}
declare module 'enzyme/src/version.js' {
  declare module.exports: $Exports<'enzyme/src/version'>;
}
declare module 'enzyme/test/_helpers/index.jsx' {
  declare module.exports: $Exports<'enzyme/test/_helpers/index'>;
}
declare module 'enzyme/test/_helpers/react-compat.js' {
  declare module.exports: $Exports<'enzyme/test/_helpers/react-compat'>;
}
declare module 'enzyme/test/ComplexSelector-spec.jsx' {
  declare module.exports: $Exports<'enzyme/test/ComplexSelector-spec'>;
}
declare module 'enzyme/test/Debug-spec.jsx' {
  declare module.exports: $Exports<'enzyme/test/Debug-spec'>;
}
declare module 'enzyme/test/ReactWrapper-spec.jsx' {
  declare module.exports: $Exports<'enzyme/test/ReactWrapper-spec'>;
}
declare module 'enzyme/test/ShallowTraversal-spec.jsx' {
  declare module.exports: $Exports<'enzyme/test/ShallowTraversal-spec'>;
}
declare module 'enzyme/test/ShallowWrapper-spec.jsx' {
  declare module.exports: $Exports<'enzyme/test/ShallowWrapper-spec'>;
}
declare module 'enzyme/test/staticRender-spec.jsx' {
  declare module.exports: $Exports<'enzyme/test/staticRender-spec'>;
}
declare module 'enzyme/test/Utils-spec.jsx' {
  declare module.exports: $Exports<'enzyme/test/Utils-spec'>;
}
declare module 'enzyme/withDom.js' {
  declare module.exports: $Exports<'enzyme/withDom'>;
}
