// flow-typed signature: 34140f16a8448b221b96e19e3b4a468d
// flow-typed version: <<STUB>>/eslint-config-jss_v^3.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-jss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-jss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-jss/index' {
  declare module.exports: $Exports<'eslint-config-jss'>;
}
declare module 'eslint-config-jss/index.js' {
  declare module.exports: $Exports<'eslint-config-jss'>;
}
