// flow-typed signature: 37f538fa8c521a30928b16dd91508c7b
// flow-typed version: <<STUB>>/is-observable_v^0.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-observable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-observable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-observable/index' {
  declare module.exports: $Exports<'is-observable'>;
}
declare module 'is-observable/index.js' {
  declare module.exports: $Exports<'is-observable'>;
}
