// flow-typed signature: 2ad391ffa9b414bdcc1249c381b115c7
// flow-typed version: <<STUB>>/is-react-prop_v1.0.0-beta.4/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-react-prop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-react-prop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-react-prop/checkAttr' {
  declare module.exports: any;
}

declare module 'is-react-prop/client/checkAttr' {
  declare module.exports: any;
}

declare module 'is-react-prop/client/createDomElem' {
  declare module.exports: any;
}

declare module 'is-react-prop/client/domElements' {
  declare module.exports: any;
}

declare module 'is-react-prop/client/index' {
  declare module.exports: any;
}

declare module 'is-react-prop/client/reactProps' {
  declare module.exports: any;
}

declare module 'is-react-prop/client/whitelists/events' {
  declare module.exports: any;
}

declare module 'is-react-prop/client/whitelists/html' {
  declare module.exports: any;
}

declare module 'is-react-prop/client/whitelists/index' {
  declare module.exports: any;
}

declare module 'is-react-prop/client/whitelists/react' {
  declare module.exports: any;
}

declare module 'is-react-prop/client/whitelists/schema' {
  declare module.exports: any;
}

declare module 'is-react-prop/client/whitelists/svg' {
  declare module.exports: any;
}

declare module 'is-react-prop/common/isCustomProp' {
  declare module.exports: any;
}

declare module 'is-react-prop/server/checkAttr' {
  declare module.exports: any;
}

declare module 'is-react-prop/server/htmlAttributes' {
  declare module.exports: any;
}

declare module 'is-react-prop/server/index' {
  declare module.exports: any;
}

declare module 'is-react-prop/server/reactProps' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-react-prop/checkAttr.js' {
  declare module.exports: $Exports<'is-react-prop/checkAttr'>;
}
declare module 'is-react-prop/client/checkAttr.js' {
  declare module.exports: $Exports<'is-react-prop/client/checkAttr'>;
}
declare module 'is-react-prop/client/createDomElem.js' {
  declare module.exports: $Exports<'is-react-prop/client/createDomElem'>;
}
declare module 'is-react-prop/client/domElements.js' {
  declare module.exports: $Exports<'is-react-prop/client/domElements'>;
}
declare module 'is-react-prop/client/index.js' {
  declare module.exports: $Exports<'is-react-prop/client/index'>;
}
declare module 'is-react-prop/client/reactProps.js' {
  declare module.exports: $Exports<'is-react-prop/client/reactProps'>;
}
declare module 'is-react-prop/client/whitelists/events.js' {
  declare module.exports: $Exports<'is-react-prop/client/whitelists/events'>;
}
declare module 'is-react-prop/client/whitelists/html.js' {
  declare module.exports: $Exports<'is-react-prop/client/whitelists/html'>;
}
declare module 'is-react-prop/client/whitelists/index.js' {
  declare module.exports: $Exports<'is-react-prop/client/whitelists/index'>;
}
declare module 'is-react-prop/client/whitelists/react.js' {
  declare module.exports: $Exports<'is-react-prop/client/whitelists/react'>;
}
declare module 'is-react-prop/client/whitelists/schema.js' {
  declare module.exports: $Exports<'is-react-prop/client/whitelists/schema'>;
}
declare module 'is-react-prop/client/whitelists/svg.js' {
  declare module.exports: $Exports<'is-react-prop/client/whitelists/svg'>;
}
declare module 'is-react-prop/common/isCustomProp.js' {
  declare module.exports: $Exports<'is-react-prop/common/isCustomProp'>;
}
declare module 'is-react-prop/index' {
  declare module.exports: $Exports<'is-react-prop'>;
}
declare module 'is-react-prop/index.js' {
  declare module.exports: $Exports<'is-react-prop'>;
}
declare module 'is-react-prop/server/checkAttr.js' {
  declare module.exports: $Exports<'is-react-prop/server/checkAttr'>;
}
declare module 'is-react-prop/server/htmlAttributes.js' {
  declare module.exports: $Exports<'is-react-prop/server/htmlAttributes'>;
}
declare module 'is-react-prop/server/index.js' {
  declare module.exports: $Exports<'is-react-prop/server/index'>;
}
declare module 'is-react-prop/server/reactProps.js' {
  declare module.exports: $Exports<'is-react-prop/server/reactProps'>;
}
