// flow-typed signature: 5cd0c14558a4a9ddc19f922595ed94a9
// flow-typed version: <<STUB>>/jss_v6.5.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss/dist/jss' {
  declare module.exports: any;
}

declare module 'jss/dist/jss.min' {
  declare module.exports: any;
}

declare module 'jss/flow-typed/cssom' {
  declare module.exports: any;
}

declare module 'jss/lib/backends/DomRenderer' {
  declare module.exports: any;
}

declare module 'jss/lib/backends/VirtualRenderer' {
  declare module.exports: any;
}

declare module 'jss/lib/index' {
  declare module.exports: any;
}

declare module 'jss/lib/Jss' {
  declare module.exports: any;
}

declare module 'jss/lib/plugins/ConditionalRule' {
  declare module.exports: any;
}

declare module 'jss/lib/plugins/FontFaceRule' {
  declare module.exports: any;
}

declare module 'jss/lib/plugins/index' {
  declare module.exports: any;
}

declare module 'jss/lib/plugins/KeyframeRule' {
  declare module.exports: any;
}

declare module 'jss/lib/plugins/RegularRule' {
  declare module.exports: any;
}

declare module 'jss/lib/plugins/SimpleRule' {
  declare module.exports: any;
}

declare module 'jss/lib/plugins/ViewportRule' {
  declare module.exports: any;
}

declare module 'jss/lib/PluginsRegistry' {
  declare module.exports: any;
}

declare module 'jss/lib/RulesContainer' {
  declare module.exports: any;
}

declare module 'jss/lib/sheets' {
  declare module.exports: any;
}

declare module 'jss/lib/SheetsRegistry' {
  declare module.exports: any;
}

declare module 'jss/lib/StyleSheet' {
  declare module.exports: any;
}

declare module 'jss/lib/types' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/createRule' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/findClassNames' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/findRenderer' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/generateClassName' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/getDynamicStyles' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/toCss' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/toCssValue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss/dist/jss.js' {
  declare module.exports: $Exports<'jss/dist/jss'>;
}
declare module 'jss/dist/jss.min.js' {
  declare module.exports: $Exports<'jss/dist/jss.min'>;
}
declare module 'jss/flow-typed/cssom.js' {
  declare module.exports: $Exports<'jss/flow-typed/cssom'>;
}
declare module 'jss/lib/backends/DomRenderer.js' {
  declare module.exports: $Exports<'jss/lib/backends/DomRenderer'>;
}
declare module 'jss/lib/backends/VirtualRenderer.js' {
  declare module.exports: $Exports<'jss/lib/backends/VirtualRenderer'>;
}
declare module 'jss/lib/index.js' {
  declare module.exports: $Exports<'jss/lib/index'>;
}
declare module 'jss/lib/Jss.js' {
  declare module.exports: $Exports<'jss/lib/Jss'>;
}
declare module 'jss/lib/plugins/ConditionalRule.js' {
  declare module.exports: $Exports<'jss/lib/plugins/ConditionalRule'>;
}
declare module 'jss/lib/plugins/FontFaceRule.js' {
  declare module.exports: $Exports<'jss/lib/plugins/FontFaceRule'>;
}
declare module 'jss/lib/plugins/index.js' {
  declare module.exports: $Exports<'jss/lib/plugins/index'>;
}
declare module 'jss/lib/plugins/KeyframeRule.js' {
  declare module.exports: $Exports<'jss/lib/plugins/KeyframeRule'>;
}
declare module 'jss/lib/plugins/RegularRule.js' {
  declare module.exports: $Exports<'jss/lib/plugins/RegularRule'>;
}
declare module 'jss/lib/plugins/SimpleRule.js' {
  declare module.exports: $Exports<'jss/lib/plugins/SimpleRule'>;
}
declare module 'jss/lib/plugins/ViewportRule.js' {
  declare module.exports: $Exports<'jss/lib/plugins/ViewportRule'>;
}
declare module 'jss/lib/PluginsRegistry.js' {
  declare module.exports: $Exports<'jss/lib/PluginsRegistry'>;
}
declare module 'jss/lib/RulesContainer.js' {
  declare module.exports: $Exports<'jss/lib/RulesContainer'>;
}
declare module 'jss/lib/sheets.js' {
  declare module.exports: $Exports<'jss/lib/sheets'>;
}
declare module 'jss/lib/SheetsRegistry.js' {
  declare module.exports: $Exports<'jss/lib/SheetsRegistry'>;
}
declare module 'jss/lib/StyleSheet.js' {
  declare module.exports: $Exports<'jss/lib/StyleSheet'>;
}
declare module 'jss/lib/types.js' {
  declare module.exports: $Exports<'jss/lib/types'>;
}
declare module 'jss/lib/utils/createRule.js' {
  declare module.exports: $Exports<'jss/lib/utils/createRule'>;
}
declare module 'jss/lib/utils/findClassNames.js' {
  declare module.exports: $Exports<'jss/lib/utils/findClassNames'>;
}
declare module 'jss/lib/utils/findRenderer.js' {
  declare module.exports: $Exports<'jss/lib/utils/findRenderer'>;
}
declare module 'jss/lib/utils/generateClassName.js' {
  declare module.exports: $Exports<'jss/lib/utils/generateClassName'>;
}
declare module 'jss/lib/utils/getDynamicStyles.js' {
  declare module.exports: $Exports<'jss/lib/utils/getDynamicStyles'>;
}
declare module 'jss/lib/utils/toCss.js' {
  declare module.exports: $Exports<'jss/lib/utils/toCss'>;
}
declare module 'jss/lib/utils/toCssValue.js' {
  declare module.exports: $Exports<'jss/lib/utils/toCssValue'>;
}
