// flow-typed signature: c3ac7f7e97abbc1d8925d58d3d6a3e08
// flow-typed version: <<STUB>>/jss_v9.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss/dist/jss' {
  declare module.exports: any;
}

declare module 'jss/dist/jss.min' {
  declare module.exports: any;
}

declare module 'jss/flow-typed/cssom' {
  declare module.exports: any;
}

declare module 'jss/lib/index' {
  declare module.exports: any;
}

declare module 'jss/lib/Jss' {
  declare module.exports: any;
}

declare module 'jss/lib/plugins/observables' {
  declare module.exports: any;
}

declare module 'jss/lib/plugins/rules' {
  declare module.exports: any;
}

declare module 'jss/lib/PluginsRegistry' {
  declare module.exports: any;
}

declare module 'jss/lib/renderers/DomRenderer' {
  declare module.exports: any;
}

declare module 'jss/lib/renderers/VirtualRenderer' {
  declare module.exports: any;
}

declare module 'jss/lib/RuleList' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/ConditionalRule' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/FontFaceRule' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/KeyframesRule' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/SimpleRule' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/StyleRule' {
  declare module.exports: any;
}

declare module 'jss/lib/rules/ViewportRule' {
  declare module.exports: any;
}

declare module 'jss/lib/sheets' {
  declare module.exports: any;
}

declare module 'jss/lib/SheetsManager' {
  declare module.exports: any;
}

declare module 'jss/lib/SheetsRegistry' {
  declare module.exports: any;
}

declare module 'jss/lib/StyleSheet' {
  declare module.exports: any;
}

declare module 'jss/lib/types' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/cloneStyle' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/createGenerateClassName' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/createRule' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/findClassNames' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/getDynamicStyles' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/isDynamicValue' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/linkRule' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/toCss' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/toCssValue' {
  declare module.exports: any;
}

declare module 'jss/lib/utils/updateStyle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss/dist/jss.js' {
  declare module.exports: $Exports<'jss/dist/jss'>;
}
declare module 'jss/dist/jss.min.js' {
  declare module.exports: $Exports<'jss/dist/jss.min'>;
}
declare module 'jss/flow-typed/cssom.js' {
  declare module.exports: $Exports<'jss/flow-typed/cssom'>;
}
declare module 'jss/lib/index.js' {
  declare module.exports: $Exports<'jss/lib/index'>;
}
declare module 'jss/lib/Jss.js' {
  declare module.exports: $Exports<'jss/lib/Jss'>;
}
declare module 'jss/lib/plugins/observables.js' {
  declare module.exports: $Exports<'jss/lib/plugins/observables'>;
}
declare module 'jss/lib/plugins/rules.js' {
  declare module.exports: $Exports<'jss/lib/plugins/rules'>;
}
declare module 'jss/lib/PluginsRegistry.js' {
  declare module.exports: $Exports<'jss/lib/PluginsRegistry'>;
}
declare module 'jss/lib/renderers/DomRenderer.js' {
  declare module.exports: $Exports<'jss/lib/renderers/DomRenderer'>;
}
declare module 'jss/lib/renderers/VirtualRenderer.js' {
  declare module.exports: $Exports<'jss/lib/renderers/VirtualRenderer'>;
}
declare module 'jss/lib/RuleList.js' {
  declare module.exports: $Exports<'jss/lib/RuleList'>;
}
declare module 'jss/lib/rules/ConditionalRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/ConditionalRule'>;
}
declare module 'jss/lib/rules/FontFaceRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/FontFaceRule'>;
}
declare module 'jss/lib/rules/KeyframesRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/KeyframesRule'>;
}
declare module 'jss/lib/rules/SimpleRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/SimpleRule'>;
}
declare module 'jss/lib/rules/StyleRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/StyleRule'>;
}
declare module 'jss/lib/rules/ViewportRule.js' {
  declare module.exports: $Exports<'jss/lib/rules/ViewportRule'>;
}
declare module 'jss/lib/sheets.js' {
  declare module.exports: $Exports<'jss/lib/sheets'>;
}
declare module 'jss/lib/SheetsManager.js' {
  declare module.exports: $Exports<'jss/lib/SheetsManager'>;
}
declare module 'jss/lib/SheetsRegistry.js' {
  declare module.exports: $Exports<'jss/lib/SheetsRegistry'>;
}
declare module 'jss/lib/StyleSheet.js' {
  declare module.exports: $Exports<'jss/lib/StyleSheet'>;
}
declare module 'jss/lib/types.js' {
  declare module.exports: $Exports<'jss/lib/types'>;
}
declare module 'jss/lib/utils/cloneStyle.js' {
  declare module.exports: $Exports<'jss/lib/utils/cloneStyle'>;
}
declare module 'jss/lib/utils/createGenerateClassName.js' {
  declare module.exports: $Exports<'jss/lib/utils/createGenerateClassName'>;
}
declare module 'jss/lib/utils/createRule.js' {
  declare module.exports: $Exports<'jss/lib/utils/createRule'>;
}
declare module 'jss/lib/utils/findClassNames.js' {
  declare module.exports: $Exports<'jss/lib/utils/findClassNames'>;
}
declare module 'jss/lib/utils/getDynamicStyles.js' {
  declare module.exports: $Exports<'jss/lib/utils/getDynamicStyles'>;
}
declare module 'jss/lib/utils/isDynamicValue.js' {
  declare module.exports: $Exports<'jss/lib/utils/isDynamicValue'>;
}
declare module 'jss/lib/utils/linkRule.js' {
  declare module.exports: $Exports<'jss/lib/utils/linkRule'>;
}
declare module 'jss/lib/utils/toCss.js' {
  declare module.exports: $Exports<'jss/lib/utils/toCss'>;
}
declare module 'jss/lib/utils/toCssValue.js' {
  declare module.exports: $Exports<'jss/lib/utils/toCssValue'>;
}
declare module 'jss/lib/utils/updateStyle.js' {
  declare module.exports: $Exports<'jss/lib/utils/updateStyle'>;
}
