// flow-typed signature: 2c679f98bf6fc006ee4d2936930e610d
// flow-typed version: <<STUB>>/react-dom-elements_v0.0.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dom-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dom-elements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dom-elements/lib/index' {
  declare module.exports: any;
}

declare module 'react-dom-elements/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dom-elements/lib/index.js' {
  declare module.exports: $Exports<'react-dom-elements/lib/index'>;
}
declare module 'react-dom-elements/src/index.js' {
  declare module.exports: $Exports<'react-dom-elements/src/index'>;
}
