// flow-typed signature: 98a0b6bfa7b2e67c15bc6bd65d60bbc9
// flow-typed version: <<STUB>>/react-jss_v^6.1.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-jss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-jss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-jss/dist/react-jss' {
  declare module.exports: any;
}

declare module 'react-jss/dist/react-jss.min' {
  declare module.exports: any;
}

declare module 'react-jss/karma.conf' {
  declare module.exports: any;
}

declare module 'react-jss/lib/compose' {
  declare module.exports: any;
}

declare module 'react-jss/lib/createHoc' {
  declare module.exports: any;
}

declare module 'react-jss/lib/createInjectSheet' {
  declare module.exports: any;
}

declare module 'react-jss/lib/getDisplayName' {
  declare module.exports: any;
}

declare module 'react-jss/lib/index' {
  declare module.exports: any;
}

declare module 'react-jss/lib/index.test' {
  declare module.exports: any;
}

declare module 'react-jss/lib/jss' {
  declare module.exports: any;
}

declare module 'react-jss/lib/SheetsRegistryProvider' {
  declare module.exports: any;
}

declare module 'react-jss/tests.webpack' {
  declare module.exports: any;
}

declare module 'react-jss/tests/compose' {
  declare module.exports: any;
}

declare module 'react-jss/tests/createHoc' {
  declare module.exports: any;
}

declare module 'react-jss/tests/createInjectSheet' {
  declare module.exports: any;
}

declare module 'react-jss/tests/getDisplayName' {
  declare module.exports: any;
}

declare module 'react-jss/tests/index' {
  declare module.exports: any;
}

declare module 'react-jss/tests/index.test' {
  declare module.exports: any;
}

declare module 'react-jss/tests/jss' {
  declare module.exports: any;
}

declare module 'react-jss/tests/SheetsRegistryProvider' {
  declare module.exports: any;
}

declare module 'react-jss/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-jss/dist/react-jss.js' {
  declare module.exports: $Exports<'react-jss/dist/react-jss'>;
}
declare module 'react-jss/dist/react-jss.min.js' {
  declare module.exports: $Exports<'react-jss/dist/react-jss.min'>;
}
declare module 'react-jss/karma.conf.js' {
  declare module.exports: $Exports<'react-jss/karma.conf'>;
}
declare module 'react-jss/lib/compose.js' {
  declare module.exports: $Exports<'react-jss/lib/compose'>;
}
declare module 'react-jss/lib/createHoc.js' {
  declare module.exports: $Exports<'react-jss/lib/createHoc'>;
}
declare module 'react-jss/lib/createInjectSheet.js' {
  declare module.exports: $Exports<'react-jss/lib/createInjectSheet'>;
}
declare module 'react-jss/lib/getDisplayName.js' {
  declare module.exports: $Exports<'react-jss/lib/getDisplayName'>;
}
declare module 'react-jss/lib/index.js' {
  declare module.exports: $Exports<'react-jss/lib/index'>;
}
declare module 'react-jss/lib/index.test.js' {
  declare module.exports: $Exports<'react-jss/lib/index.test'>;
}
declare module 'react-jss/lib/jss.js' {
  declare module.exports: $Exports<'react-jss/lib/jss'>;
}
declare module 'react-jss/lib/SheetsRegistryProvider.js' {
  declare module.exports: $Exports<'react-jss/lib/SheetsRegistryProvider'>;
}
declare module 'react-jss/tests.webpack.js' {
  declare module.exports: $Exports<'react-jss/tests.webpack'>;
}
declare module 'react-jss/tests/compose.js' {
  declare module.exports: $Exports<'react-jss/tests/compose'>;
}
declare module 'react-jss/tests/createHoc.js' {
  declare module.exports: $Exports<'react-jss/tests/createHoc'>;
}
declare module 'react-jss/tests/createInjectSheet.js' {
  declare module.exports: $Exports<'react-jss/tests/createInjectSheet'>;
}
declare module 'react-jss/tests/getDisplayName.js' {
  declare module.exports: $Exports<'react-jss/tests/getDisplayName'>;
}
declare module 'react-jss/tests/index.js' {
  declare module.exports: $Exports<'react-jss/tests/index'>;
}
declare module 'react-jss/tests/index.test.js' {
  declare module.exports: $Exports<'react-jss/tests/index.test'>;
}
declare module 'react-jss/tests/jss.js' {
  declare module.exports: $Exports<'react-jss/tests/jss'>;
}
declare module 'react-jss/tests/SheetsRegistryProvider.js' {
  declare module.exports: $Exports<'react-jss/tests/SheetsRegistryProvider'>;
}
declare module 'react-jss/webpack.config.js' {
  declare module.exports: $Exports<'react-jss/webpack.config'>;
}
