// flow-typed signature: f25acde0699da70b4176deef047ad679
// flow-typed version: <<STUB>>/zen-observable_v^0.6.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zen-observable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zen-observable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zen-observable/src/Observable' {
  declare module.exports: any;
}

declare module 'zen-observable/test/default' {
  declare module.exports: any;
}

declare module 'zen-observable/test/filter' {
  declare module.exports: any;
}

declare module 'zen-observable/test/flatMap' {
  declare module.exports: any;
}

declare module 'zen-observable/test/map' {
  declare module.exports: any;
}

declare module 'zen-observable/test/reduce' {
  declare module.exports: any;
}

declare module 'zen-observable/test/species' {
  declare module.exports: any;
}

declare module 'zen-observable/test/symbol' {
  declare module.exports: any;
}

declare module 'zen-observable/util/build' {
  declare module.exports: any;
}

declare module 'zen-observable/zen-observable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zen-observable/index' {
  declare module.exports: $Exports<'zen-observable'>;
}
declare module 'zen-observable/index.js' {
  declare module.exports: $Exports<'zen-observable'>;
}
declare module 'zen-observable/src/Observable.js' {
  declare module.exports: $Exports<'zen-observable/src/Observable'>;
}
declare module 'zen-observable/test/default.js' {
  declare module.exports: $Exports<'zen-observable/test/default'>;
}
declare module 'zen-observable/test/filter.js' {
  declare module.exports: $Exports<'zen-observable/test/filter'>;
}
declare module 'zen-observable/test/flatMap.js' {
  declare module.exports: $Exports<'zen-observable/test/flatMap'>;
}
declare module 'zen-observable/test/map.js' {
  declare module.exports: $Exports<'zen-observable/test/map'>;
}
declare module 'zen-observable/test/reduce.js' {
  declare module.exports: $Exports<'zen-observable/test/reduce'>;
}
declare module 'zen-observable/test/species.js' {
  declare module.exports: $Exports<'zen-observable/test/species'>;
}
declare module 'zen-observable/test/symbol.js' {
  declare module.exports: $Exports<'zen-observable/test/symbol'>;
}
declare module 'zen-observable/util/build.js' {
  declare module.exports: $Exports<'zen-observable/util/build'>;
}
declare module 'zen-observable/zen-observable.js' {
  declare module.exports: $Exports<'zen-observable/zen-observable'>;
}
