// flow-typed signature: 247bd0f0fb67c476dd58bf82ba5163ed
// flow-typed version: <<STUB>>/@lttb/eslint-config-default_vgithub:lttb/configs#js/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lttb/eslint-config-default'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@lttb/eslint-config-default' {
  declare module.exports: any;
}
